= The template for writing documents

This repository is the template that define envirinment for writing document site on some Linux distributions.

Goals is here.

* Can writing documents via reStructuredText
** Use sphinx
* Can start easily.
** only clone this repository, or execute only one command.
* Can incremental build documents
* Can publish as single site that is able to open in local without any server.
* Can not export pdf with entirely documents
** So PDF searchability is poor. Searchability of documentations is very important feature for documentation I think

Not goals of this repository.

* Run on any platform
** To be able to run linux on Windows with some virtualizations also VirtualBox, Hyper-V, VMware and others, macOS same.

=======
Should clone each document root? Not need. Read Install section.
=======

== Requirements

WARNING: Requirements for this repository are changes frequency. Because I optimize environment and writing method something.

* nodejs + npm
** To use as an alternative for the `make` command.
* Docker
** To run hugo/asciidoctor.

== Installation ==

1. Clone this repository to any location you like
2. Delete .git directory if you need
3. Run ++npm install++ (only once)
4. Run ++npm run init++ (Needs if you first use this template)
5. Run ++npm run new++ (only once)
6. You can writing in the location cloned as you like with the Hugo\'s way.

== Toolchain ==
This scafford contains toolchains below.

* Sphinx
** Use Read The Doc theme
** sphinxcontrib-blockdiag
** sphinxcontrib-seqdiag
** sphinx-autobuild
* draw.io
** Use to draw complex drawing

== Write documents

You can run hugo server with the command below in your documentation directory.

NOTE: Your user must be on the docker group.

[source, shell]
----
$ npm run
----

You visit from browser at http://localhost:1313 , you should be able to show generated site via Hugo!

Execute command if you stop server.

[source, shell]
----
$ npm run stop
----

.Building static site
[source, shell]
----
$ npm run build
----
