= The writing scafford

This repository is the scafford that define envirinment for writing document on some Linux distributions.

Goals is here.

* Can start easily.
** only clone this repository, or execute only one command.
* Can incremental build documents
** Include live-reload server.
* Can publish some format
** include html/pdf/epub ..

Not goals of this repository.

* Run on any platform
** Using platforms by me are Windows and Linux, not include macOS.
** To be able to run linux on Windows with some virtualizations also VirtualBox, Hyper-V, VMware and others, macOS same.

=======
Should clone each document root? Not need. Read Install section.
=======

== Requirements

WARNING: Requirements for this repository are changes frequency. Because I optimize environment and writing method something.

* Docker
** To run asciidoctor.

== Install ==

1. Clone this repository to any location you like
2. Run ++./writing init++ (only once)
3. Run ++./writing install <directory>++
4. You can writing in the path ++<directory>++ initialized above

== Toolchain ==
This scafford contains toolchains below.

* asciidoctor
* asciidoctor-diagram
** Enable mermaid
* asciidoctor-pdf
** Enable publish pdf

== Usage

All your documents wrote by asciidoc must be in ++src++ directory.

While writing, when you want to build your documents, type command follow.

[source, shell]
----
$ ./writing build
----

If you felt tired to type build command each editing, you can launch automation-build server with follow command.

NOTE: Your user must be on wheel group.

[source, shell]
----
$ ./writing serve
# Stop servers
$ ./writing stop
----

After above command, when you edit documents, then build and output it to ++public++ directory! And you can view it on browser at http://localhost:3000 .

=== Publish PDF ===
If you want to publish document as pdf, you should hold by follows.

* The name of document root must be *index.adoc*
* Themes are located at `assets/pdf/themes`
* Fonts used in pdf document are located at `assets/pdf/fonts`

Then, execute command below. Output document built as `public/name.pdf`.

[source, shell]
----
$ ./writing build-pdf <name> [name of theme]
----

