= The writing scafford

This repository is the scafford that define envirinment for writing document on some Linux distributions.

Goals is here.

* Can start easily.
** only clone this repository, or execute only one command.
* Can incremental build documents
** Include live-reload server.

Not goals of this repository.

* Run every platform
** Using platforms by me are Windows and Linux, not include macOS.
** To be able to run linux on Windows with some virtualizations also VirtualBox, Hyper-V, VMware and others, macOS same.

== Requirements

WARNING: Requirements for this repository are changes frequency. Because I optimize environment and writing method something.

* Docker
** To run asciidoctor.
* Asciidoctor (Optional)
** If your environment can not install docker, you must install it.

== Install ==

1. Clone this repository to any location as you like.
2. Run ++./writing init++

== Usage

All your documents wrote by asciidoc must be in ++src++ directory.

While writing, when you want to build your documents, type command follow.

NOTE: Must exist ++src/index.adoc++ to build document.

[source, shell]
----
$ ./writing build
----

If you felt tired to type build command each editing, you can launch automation-build server with follow command.

NOTE: Your user must be on wheel group.

[source, shell]
----
$ ./writing launch-server
----

After above command, when you edit documents, then build and output it to ++public++ directory! And you can view it on browser at http://localhost:3000 .
